version: "3.7"
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poc
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
