# Generated by Django 3.2.4 on 2021-06-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='app_user',
        ),
    ]
