# Generated by Django 3.2.4 on 2021-06-10 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('box_integration', '0002_auto_20210609_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='box_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_authorized_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='boxconfig',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
